# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  compile:

    runs-on: ubuntu-latest

    name: Running Java ${{ matrix.java }} compile

    steps:

    - uses: actions/checkout@v2

    - name: Set up JDK 1.11

      uses: actions/setup-java@v1

      with:

        java-version: 1.11
    - name: Cache the Maven packages to speed up build
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2    

    - name: Compile code

      run: mvn compile

  test:

    runs-on: ubuntu-latest

    name: Running tests

    needs: compile

    steps:

      - uses: actions/checkout@v2

      - name: Set up JDK 1.11

        uses: actions/setup-java@v1

        with:

          java-version: 1.11

      - name: Run unit tests

        run: mvn test
  build:

    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml 
  build-docker-image:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    needs: [build_and_test]

    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Container image
        run: docker build -t ${{ secrets.DOCKERHUB_REPO }}:latest1 .
      - name: Publish Docker image
        run: docker push ${{ secrets.DOCKERHUB_REPO }}
